const questionsTruth = [
  "If you had to erase one person in this room from your memory right now (as if you had never met), who would it be and why?",
  "What is the weirdest, cringiest, or most inexplicable thing you’ve done while completely alone in a room?",
  "If you were offered $1,000,000 to permanently end all contact with your best friend, would you take it? Be honest.",
  "What is the wildest lie you’ve told someone directly to their face that they still believe to this day?",
  "If you could view anyone in this room's browser history for the entire past year, whose history would you choose?",
  "Was there a moment when you were genuinely happy about someone here failing or experiencing a setback? What was it for?",
  "What action in your life do you regret the most, but have never told anyone about until now?",
  "Who in this group annoys you the most, even if you don't show it?",
  "If you had to frame someone in this room for a crime they didn't commit to save yourself from police, who would you pick?",
  "What is your most unpopular or weird opinion that would get you severely judged in polite society?",
  "If you had to listen to only one artist from someone's playlist in this room for the rest of your life, whose playlist would you pick?",
  "If you could painlessly and covertly read the mind of one person in this room right now, who would it be?",
  "What is the dumbest or most embarrassing thing you’ve Googled in the past few days?",
  "If you committed a crime and urgently needed to hide the evidence, who in this room would you trust, and who would you definitely NOT trust?",
  "Have you ever stalked someone on social media using a fake account? Who was it and why?",
  "If you had to swap lives with someone in this room for a week, who would you choose?",
  "What is the largest amount of money you’ve spent on an absolutely useless or cringey item?",
  "If you could permanently ban one person here from using a specific phrase or filler word, what would it be?",
  "What first impression did you have of the person sitting to your right that turned out to be completely wrong?",
  "Have you ever accidentally (or intentionally) eavesdropped on a private conversation meant for other ears? What did you hear?",
  "If you had to spend a month on a deserted island with one person from this room, who would drive you completely insane?",
  "What is the most absurd excuse you’ve made up to avoid going to a hangout or party simply because you were lazy?",
  "If you were legally allowed to commit one crime without consequences, what would you do?",
  "What is your biggest fear regarding what other people think of you?",
  "If you had to choose right now between deleting all your social media accounts forever or showing your last month's Google search history to everyone in this room, which would you pick?",
  "What is the cringiest text message or voice note you’ve sent by mistake to the wrong person?",
  "Is there a person in this room whose approval or praise matters to you the most, even if you hide it?",
  "If you could secretly bug someone's house in this group with a listening device, who would you spy on?",
  "What secret or embarrassing fact about you is known by at least one person here that you are terrified they might spill?",
  "If you had to sincerely compliment the person you like least in this group right now, what would you praise them for?",
  "What wild or weird conspiracy theory do you secretly believe is 100% true?",
  "If you could instantly find out one fact about your future (like your death date or your spouse's name), would you take the chance?",
  "Was there a time you pretended to love a gift from someone present here when it was actually terrible?",
  "If a hidden camera followed your every move for a week, what action or habit of yours would shock viewers the most?",
  "What habit do you engage in regularly knowing it slowly ruins your life or health, but you just can't stop?",
  "If you could change one personality trait of the person sitting opposite you, what would you change?",
  "What is the dumbest or most unfounded rumor you've heard about yourself, and how did you react?",
  "If you had to transfer all your property and assets to one person in this room right now, who would you trust with your savings?",
  "What is something you really want to do in the coming year, but fear your friends or family will harshly judge you for?",
  "If you had to permanently cut ties with one person in this room right now to save your career or education, who would it be?",
  "What is the stupidest thing you’ve done just to impress someone you had a massive crush on?",
  "What secret or embarrassing detail have you lied about even to your best friend or partner?",
  "If you could secretly delete one social media account belonging to anyone here, whose profile would you wipe off the face of the earth?",
  "Have you ever faked an illness, injury, or severe distress just to get attention or sympathy from someone?",
  "What is the harshest or most offensive message you wrote about someone in this room in the third person in another chat, but never sent (or deleted)?",
  "If offered the chance to know the exact date and cause of death of anyone in this room, would you want to hear it?",
  "What item did you take without permission (stole or forgot to return) from an acquaintance, and the owner still thinks it's just lost?",
  "If you had to spend 48 hours locked in a room one-on-one with the person here you like the least, how would you pass the time?",
  "What past action of yours still makes you wake up in the middle of the night cringing with intense shame?",
  "If you could eavesdrop on a private conversation between your parents or close ones talking specifically about you without getting caught, would you do it?",
  "What is the weirdest, dumbest, or most dangerous thing you’ve ever impulse-bought on the internet?",
  "Was there a moment in your life when you intentionally threw someone else under the bus (at work, school, or in a group) just to get yourself off the hook?",
  "If you had to genuinely confess your love or strong affection to someone in this room right now (even friendly), who would be the hardest to say it to?",
  "What trait of your personality or appearance do you consider your greatest asset, but never admit out loud due to modesty?",
  "If you had to pick one person in this room right now and reveal their most embarrassing secret to everyone present, who would it be?",
  "What is the most selfish thing you’ve done in your life that hurt someone else, but you don't regret in the slightest?",
  "If you could secretly erase one memory of a mistake you made from the mind of the person sitting to your left, what would you erase?",
  "Was there a point when you genuinely hated someone in this room? What caused it?",
  "What is your weirdest or most unsettling personality trait that you carefully hide behind a 'nice and friendly' mask?",
  "If you had to choose one person in this room whose life you would guaranteed save at the cost of everyone else hating you forever, who would it be?",
  "What is the cringiest thing you’ve done at someone's house in this group while the host stepped away for a couple of minutes?",
  "If you had to borrow a large sum of money right now and never pay it back, who in this room would you ask?",
  "Have you ever intentionally spread rumors or turned mutual acquaintances against someone in this room?",
  "What is the most ridiculous, dumb, or bizarre dream featuring someone in this room you've ever had?",
  "If you had to point out one quality in yourself that most often causes people to stop talking to you, what would it be?",
  "What is the biggest lie you are currently maintaining in your relationship with your parents or close ones?",
  "If you could find out one hidden fact about the private life of the person sitting opposite you, what would you want to know?",
  "Have you ever read someone's private messages (on a friend's, partner's, or parent's phone) while they left the screen unlocked?",
  "If you had to move to another country forever right now and bring only one person from this room, who would you choose?",
  "If you learned that someone in this room secretly has a crush on you, whose name would scare or disappoint you the most?",
  "What is the dumbest, most petty, or childish grudge you still hold against someone present?",
  "If you had to send the last three screenshots in your gallery to your main group chat right now, which one would make you feel most embarrassed?",
  "Have you ever faked a chat conversation or doctored a screenshot to prove you were right or to set someone up?",
  "If you could become invisible for one week, whose home or workplace/school among those present would you spy on first?",
  "What habit or behavioral quirk of yours does your family consider completely abnormal, yet you persistently keep doing it?",
  "If offered to erase the past year of your life in exchange for an ideal relationship with the person of your dreams right now, would you agree?",
  "Have you ever taken someone else's belongings (makeup, clothes, perfume, headphones) without asking while no one was looking, and then neatly put them back?",
  "What is the weirdest or most inappropriate place you’ve fallen asleep due to sheer exhaustion or alcohol?",
  "If you had to rate the sincerity level of everyone in this room on a scale from 1 to 10 right now, who would get the lowest score?",
  "What wild or uncomfortable truth about yourself do you hide on a first date or when meeting new people?",
  "Was there a moment in your life when you genuinely regretted getting involved and becoming friends with someone in this room?",
  "What embarrassing song (like 90s pop or kids' tracks) do you love listening to in your headphones when no one is watching?",
  "If you had to block one person present on all social media without explanation for a whole month right now, who would it be?",
  "What advice or statement from your parents do you consider complete nonsense, but pretend to agree with fully in public?",
  "If you had to choose one person in this room whose secrets you’d expose to save your own reputation, who would it be?",
  "What is the dumbest or weirdest lie you’ve made up about your financial situation or status just to look cool in front of acquaintances?",
  "If you could secretly erase from the memory of the person to your right any single achievement or victory they are proud of, would you do it?",
  "Was there a moment in your life when you were genuinely happy about the breakup or fight of a couple in your close friend circle?",
  "What is the cringiest thing you’ve done on social media while trying to get the attention of someone who ignored you?",
  "If you had to pick one person in this room to share a single bank account and all income with for the rest of your life, who would you choose?",
  "What is the most embarrassing or absurd thing you accidentally left at someone's house/hotel/taxi and were too ashamed to go back for?",
  "If you had to confess one hidden vice or bad habit that no one here suspects right now, what would it be?",
  "Have you ever faked being super drunk or feeling sick just to leave a boring hangout or date?",
  "What is your biggest fear regarding people in this room seeing you in a completely informal or home environment?",
  "What is the wildest or weirdest thing you’ve ever spied on your neighbors doing (through a window, fence, or keyhole)?",
  "If you had to name the person in this room who you think will achieve the least success in life, who would it be?",
  "What is the dumbest line you’ve said in an important interview, exam, or meeting that made you want to sink through the floor?",
  "If legally allowed to read the private diary of anyone in the world for their entire life, whose diary would you pick?",
  "Have you ever intentionally damaged or hidden an item belonging to your sibling/friend out of fleeting jealousy or anger?",
  "If you had to assign horror movie roles to everyone present right now, who would die first, and who would survive until the end?",
  "What is the biggest foolishness you committed due to peer pressure, just because your group was doing it, even though you disliked it?",
  "If you could instantly find out one hidden fact that your partner or best friend is keeping from you, would you take the chance or be afraid?",
  "Was there a case when you were genuinely glad that a close friend's important plans or trip fell through because you were staying home yourself?",
  "What is the cringiest thing you wrote or Googled during severe emotional burnout or in the middle of the night when you couldn't sleep?",
  "If you had to pick one person in this room whose opinion about you matters the least (completely indifferent), who would it be?",
  "What is the most expensive item you accidentally broke, ruined, or lost at someone's place, but covered it up by blaming luck or pets?",
  "If you had to rewrite your message history with anyone in this room so everyone present could read it, whose name would you pick?",
  "Have you ever faked amnesia, extreme fatigue, or 'not noticing' a message/call just to avoid a difficult conversation?",
  "What is your weirdest or most absurd superstition that you secretly believe in and follow, even if you laugh at it in public?",
  "If you had to name the person in this group who you think has the most specific or strange taste in music or clothing, who would it be?",
  "What is the most absurd, childish, or weird reason you’ve used to break up with someone or stop talking to them?",
  "Was there a moment when you deliberately took credit for someone else's work (at job, school, or in creative tasks) and got praised for it?",
  "If offered free plastic surgery or a physical feature modification with a 100% success guarantee right now, what would you change?",
  "What is the most embarrassing lie you’ve told a teacher or boss to justify a major absence or missed deadline?",
  "If you had to point out one action by anyone in this room that made you feel genuine second-hand embarrassment (cringe), what would it be?",
  "What is the dumbest, made-up story about yourself you told a group of new acquaintances just so you wouldn't seem boring?",
  "If you could secretly block one person in this room on all social media accounts of their partner/best friend, who would you erase from their digital life?",
  "Was there a moment in your life when you intentionally didn't warn an acquaintance that their fly was unzipped, makeup was smudged, or clothes were stained, just to watch them be embarrassed?",
  "What is the most absurd or weird chat log you feverishly deleted from your phone out of fear that someone might see your screen?",
  "If you had to name one person in this room whose presence at the party initially made you slightly tense or disappointed, who would it be?",
  "What is the most expensive or important thing you borrowed from friends and returned slightly damaged, hoping they wouldn't notice?",
  "If you had to show your entire bank transaction history for the past month to everyone in this room right now, which purchase would make you uncomfortable?",
  "Have you ever faked deep sleep on a train, plane, or bus just to avoid talking to an annoying fellow traveler or acquaintance?",
  "What is your weirdest prejudice about people by which you unconsciously evaluate someone upon first meeting (e.g., shoes, nail shape, phone case)?",
  "If you had to name the person in this group whose social media stories or posts you scroll past thinking 'god, what cringe', who would it be?",
  "What is the dumbest, most childish, or selfish reason you’ve made up not to share food, items, or a console with your friends?",
  "Was there a moment when you intentionally pretended not to notice an acquaintance on the street or in a store and hastily turned into another aisle/alley?",
  "If offered to erase any single year from your school or university past right now, which year would you wipe out without hesitation?",
  "What is the most embarrassing lie you told yourself for a long time before finally accepting the real state of affairs?"
];

export default questionsTruth;