const questionsDare = [
  "Go to your music library, find the weirdest or most embarrassing track, and post it to your social media story with the caption: 'This is the best thing I've ever heard, on repeat for three days straight!'. Do not delete until the end of the game.",
  "Open your contacts, close your eyes, scroll, and randomly tap someone. Call them and say in a creepy, ominous voice: 'They know what you did last summer', then immediately hang up.",
  "Send a voice message to a random person in your chats (or someone you haven't talked to in a long time) and just loudly and realistically yawn/sneeze into the mic, then send it with no explanation.",
  "Swap one or two items of clothing with a person of the opposite sex in this room and stay like that for the next 3 rounds.",
  "Do 10 perfect push-ups (or attempt a handstand against the wall), but with every repetition, you must loudly and passionately shout the name of a famous actor or politician.",
  "For the next two rounds, you cannot speak in your normal voice. You must deliver all your lines either like a robot or a moody 5-year-old child.",
  "Close your eyes. Let the group mix 3 completely random edible ingredients in a glass (e.g., cola, sauce, juice, or tea), and you have to take a sip and guess what's inside.",
  "Open Instagram/Telegram, find the latest post or story from an acquaintance (not in this room), and leave a super weird but serious comment, like: 'Why are you lying to people?' or 'I'm still waiting for an explanation'.",
  "Hand your phone to the person on your right. They can go to your photos and pick any one picture (except private/intimate ones) that you must set as your messaging app profile picture for the next 24 hours.",
  "Unlock your phone, hand it to the group, close your eyes, and let them read your last 5 browser search queries out loud.",
  "Go to the window, open it, and shout out loud three times: 'I love mayonnaise more than my life!' (or any other absurd phrase chosen by the group).",
  "Call any food delivery or taxi service and try to order something they definitely don't have (e.g., a live penguin or a tractor spare part), keeping the call going for at least 1 minute.",
  "Let the group choose any word. For the next 3 rounds, you must subtly slip this word into every sentence you say without anyone noticing (if caught — penalty).",
  "Call one of your parents or close relatives and say in an anxious voice that you accidentally just bought a goat (or another large animal) and are bringing it home. Keep the suspense for 30 seconds.",
  "Until the end of the game, you become the personal servant of the person sitting opposite you: fetch water, scratch their back, or hand them things on command.",
  "Call a friend who isn't in this room and start the conversation as if you're right in the middle of a spy action movie: speak in a whisper, use code words, and abruptly hang up.",
  "Let the group blindfold you with a scarf. Then, by touch alone (only hands on face or hair), you must guess one of the people present.",
  "Take a piece of paper and a marker, hold the marker with your teeth, and try to draw a recognizable portrait of the person to your left in 1 minute without using your hands.",
  "Call a random number (or pick one together) and try to sell the person who answers a regular pen or a glass of water using hard-sell marketing tactics.",
  "Take a shot or a glass of water without using your hands — the glass must stay on the table, and you can only use your lips and teeth.",
  "Open your contacts, find someone you haven't talked to in over a year, and send them a text: 'I need to tell you something, it's urgent. Call me back as soon as you can'. Do not answer their calls for the next 10 minutes.",
  "Unlock your phone, open your gallery, close your eyes, and let the group scroll through your photos randomly. Whichever photo they stop on — you must post it to your story with no caption for 3 hours.",
  "Take your phone, open any large group chat, and send a random gibberish string of letters (e.g., 'ksjdhfkj'), then a minute later write: 'Oops, sorry, that wasn't meant for you, but for a secret chat'. Say nothing else after.",
  "For the next 3 rounds, you cannot agree with anyone in this room. To every statement or question, you must find counterarguments and debate fiercely.",
  "Let the group pick any object in this room. You must spend 2 minutes passionately and convincingly declaring your love to this object while on your knees in front of it.",
  "Take an ice cube (or something cold from the fridge) and put it down your shirt or back. You must sit like that for a full 1 minute without trying to get it out.",
  "Call any acquaintance and start the conversation with: 'Listen, I don't have much time, I'm being followed. If I don't get in touch in an hour, burn the blue folder', then abruptly turn off your phone for 5 minutes.",
  "Until the end of the game, every time someone says your name, you must make a strange sound (e.g., crow like a rooster, meow, or imitate breaking glass). Forgot — take a penalty sip of water.",
  "Give the group a marker or pen. Let them write any funny word on your forehead or arm (e.g., 'Cringe' or 'Mayonnaise'), and you cannot wash it off until the party ends.",
  "Switch seats with the person sitting furthest from you. However, you must crawl to your new spot strictly on all fours while making train sounds.",
  "Go to the page of any popular influencer or public page on social media and leave a comment under their latest post: 'I know your secret, everyone will find out soon'.",
  "Take any spice (pepper, cinnamon, or salt), pour a bit on your palm, and blow it away while sneezing loudly or acting like a wizard casting a spell.",
  "Call any local pizzeria or restaurant and try to apply for a job as a pizza crust taster, keeping a completely serious tone for at least 1 minute.",
  "For the next two rounds, you become the 'shadow' of the person to your right: you must copy all their movements, poses, and expressions with a few seconds lag.",
  "Take a hairbrush, spoon, or any household item, use it as a microphone, and rap a snippet of any heavy rap track out loud without music as expressively as possible.",
  "Open your messages, pick the person you talk to most, and send them: 'I can't hide this anymore, we need to have a serious talk about us'. After that, turn off your phone screen for 5 minutes.",
  "Give your phone to the person on your right. They get to open any app of their choice (Telegram, Instagram, Gallery) and inspect it for a full 1 minute. You cannot snatch the phone back.",
  "Take your phone, open the camera, record a video where you completely seriously declare your love to a totally random inanimate object in the room (e.g., a power outlet or trash can), and send it to your work/school chat without context.",
  "Until the end of the game, you must add cute diminutive suffixes to every word or phrase you say (e.g., 'water-y', 'chair-y', 'question-y'). Forgot — penalty point.",
  "Let the group pick any track. You must stand in the middle of the room and perform a dramatic, expressive, and hilarious dance with no music, relying only on the rhythm in your head.",
  "Take your phone, open your contacts, close your eyes, and scroll quickly. Whichever contact the group points to, you must call them and excitedly congratulate them on a fake holiday (e.g., 'National Garlic Lovers Day').",
  "For the next 3 rounds, you are not allowed to sit on a chair/couch. You must either stand on one leg or squat like a tough 90s rapper.",
  "Let the group mix a few spicy or sour ingredients on a spoon (e.g., mustard, lemon juice, and pepper). You must eat it with a completely stone-cold, emotionless poker face.",
  "Take a piece of paper, write in big letters 'I'm lost, help me find my way home', and tape it to your back (or chest). You must sit with it until the end of the game.",
  "Call a random number and try to convince the person on the line that you are a secret government agent and their phone is currently undergoing an emergency disinfection. Keep them on for 1 minute.",
  "Go to your social media and put this in your bio/status: 'Taking orders for ear-shape fortune telling. Expensive. DM me'. Do not delete until tomorrow morning.",
  "Let the person to your left blindfold you. You will be handed an object from this room, and you must guess what it is by licking it once (the object will be clean and safe, of course).",
  "For the next two rounds, you cannot say 'Yes', 'No', or use any pronouns ('I', 'You', 'He', 'She'). If you mess up — perform a mini-penalty set by the group.",
  "Take a mouthful of water and try to explain the plot of your favorite movie using only mime and gestures without spilling a drop. No spitting out the water!",
  "Give the group a marker. Let them draw pirate whiskers or funny eyeliner on your cheeks, and you must spend the rest of the night like that, even if you have to go to the store.",
  "Open your front camera, take the ugliest, cringiest selfie possible (double chin, wild face), and send it to your first follower/following on Instagram or Telegram without any context.",
  "Take your phone, open contacts, and rename the person sitting to your left to 'My Cutie Pie' (or 'Chief Cringe of the Night'). The name must stay in your phone for at least a week.",
  "Until the end of the next round, you cannot blink while looking at whoever is asking you a question or talking to you. Blinked — penalty.",
  "Let the group hand you any book, magazine, or open an article online. Your task is to read a paragraph out loud using the dramatic movie trailer voiceover tone.",
  "Take any empty plastic bottle or can, put it on the floor in the middle of the room, and spend 1 minute trying to hypnotize it with your gaze, waving your hands and whispering spells.",
  "Call a good friend and start the call with: 'Hey! Listen, do you remember where we buried that box last Tuesday? I think we've been exposed'. Keep up the panic for 30 seconds.",
  "For the next 3 rounds, every time you want to say something, you must raise your hand, wait for official permission from the group, and start with: 'Honorable jury, I would like to state...'.",
  "Hand the marker to the person opposite you. They get to draw a 'tattoo' on your palm (like a cat paw or a smiley face) that you cannot wash off until morning.",
  "Take a pinch of sugar or salt, put it on your tongue, and try to recite any tricky tongue twister three times in a row with a straight face and no pauses.",
  "Go to a mirror, stare at your reflection for 1 minute, and loudly, dramatically praise or criticize your own eyebrows, arguing with yourself.",
  "Go to any popular chat or your story and post a totally random set of emojis (e.g., 🤡🍆🦔🪓🚽) captioned: 'Finally this day has come, I've waited so long for this'.",
  "Let the group pick an article of clothing you are wearing. You must take it off and wear it inside out (or backward) for the next 3 rounds.",
  "Call any hotline or customer support (e.g., internet provider) and very politely ask the operator if they believe in aliens and whether tinfoil hats protect against Wi-Fi routers.",
  "Take two spoons, use them like castanets or drumsticks, and play a dramatic rhythm along with any conversation in the room for 1 minute.",
  "Sit on the floor, hug your knees, and roll back and forth for 30 seconds while making happy seal noises.",
  "Open your contacts, find the person you talk to least, and send them: 'I know this sounds weird, but I had a dream that we robbed a bank together. What does this mean?'. Leave them without explanation for 10 minutes.",
  "Unlock your phone, go to settings, and change the system language to Chinese, Arabic, or another complex script. You must keep it like that for the next 4 rounds.",
  "Until the end of the next round, you cannot answer questions directly. Every sentence must begin with 'As my grandfather used to say...' or 'According to ancient prophecies...'.",
  "Let the group pick any piece of furniture. Your job is to pitch and sell it to everyone present as a unique artifact that grants immortality for 1 minute.",
  "Take your phone, open the voice recorder, and record yourself doing a loud, dramatic evil villain laugh for 30 seconds, then send the audio to your family chat.",
  "Call any friend (not present) and start with: 'Hey! Listen, by any chance do you have a spare giant banana costume for tomorrow? Really need one'. Stay serious for half a minute.",
  "For the next 3 rounds, you are not allowed to use your hands to grab your phone, glass, or food. If you need something, you must ask other players like a true monarch.",
  "Give the marker to the person on your left. Let them draw a small funny detail on your cheek or neck (like a pirate scar or a tear) that cannot be washed off until the game ends.",
  "Take a pinch of cinnamon or black pepper, sniff it closely, and try to hold back a sneeze for 30 seconds while keeping a completely calm face.",
  "Go to a wall, lean your back against it, and slowly slide down while acting out a dramatic movie scene where the hero learns terrible news, whispering loudly: 'But why me?..'.",
  "Go to a random person's page from your recommendations on social media and like their oldest post (from years ago) so they know you stalked their profile deep.",
  "Let the group pick two totally incompatible food items on the table (e.g., cheese and chocolate, or chips with ketchup and tea). You must eat the combo in one bite.",
  "Call any support line or big store and completely seriously ask if they can advise you on proper care for a household ghost that started stomping too loudly at night.",
  "Take any pillow or plush toy, declare it your archenemy, and engage in a fierce non-contact shadow fight with it for 1 minute while commenting on your moves.",
  "Sit cross-legged on the floor, close your eyes, and loudly meditate for 1 minute saying 'Ommms', shifting your tone from a high squeak to a deep bass.",
  "Open your contacts, pick someone you talk to strictly for work/school, and text them: 'I feel like we've been hiding this for too long. Let's meet up'. Do not reply for 10 minutes.",
  "Unlock your phone, go to sound settings, and set the loudest, most annoying, or weirdest ringtone for calls and alarms. You must keep it until tomorrow.",
  "Until the end of the next round, every time someone addresses you, you must take a deep sigh, make a dramatic pause, look up at the ceiling, and only then answer.",
  "Let the group pick an inanimate object in the room (e.g., a chair, slipper, or mug). Your job is to scold it harshly for 1 minute for 'misbehaving'.",
  "Take your phone, turn on the front camera, and record a 15-second video trying to wiggle your ears, nostrils, or eyebrows to epic music, then post it to Close Friends.",
  "Call any acquaintance (not at the party) and start with: 'Listen, do you know why my ears ring whenever I chew raw potatoes?'. Try to hold a serious face for 30 seconds.",
  "For the next 3 rounds, you are forbidden from using the letters 'R' and 'L' in your speech. If you accidentally say a word containing them — perform a penalty (e.g., squats).",
  "Hand a marker or pen to the person on your right. Let them draw a funny face on your finger. Until the end of the game, this finger becomes your 'sidekick', and you must consult with it before every answer.",
  "Take a lemon slice (or a drop of hot sauce) and hold it on your tongue for 45 seconds while staring straight into the eyes of the person opposite you without blinking or wincing.",
  "Go to the front door (or room door), knock gently from the inside, press your ear to it, and loudly ask: 'Who's there? I wasn't expecting anyone!'. Repeat twice with a deadpan expression.",
  "Open any chat, find the last video or meme sent to you, and record a voice/video note in response where you just laugh genuinely and uncontrollably for 20 seconds, then abruptly cut off.",
  "Let the group pick two different audio tracks on phones. Play them simultaneously, and you must try to sing along to both songs at the same time for 1 minute, creating a chaotic mashup.",
  "Call any 24/7 pharmacy or support line and very politely ask if they have anything in stock for 'excessive genius' or 'common sense pills'.",
  "Take any newspaper, magazine, or open a news site. Pick a random headline and read it out loud as if you are a medieval town crier announcing a royal decree in the town square.",
  "Sit on the floor, cross your legs, close your eyes, and spend 1 minute making faulty microphone static/squeal/popping sounds whenever anyone in the room starts talking.",
  "Open your messaging app, find the person you talk to least, and send them a random coffin ⚰️ or ghost 👻 emoji with no text. Do not reply to them for the next 15 minutes.",
  "Unlock your phone, set the screen brightness to maximum and auto-lock screen timeout to the shortest option. You must play like this for the rest of the night.",
  "Until the end of the next round, every time someone uses a question word ('What?', 'Where?', 'Why?', 'How?'), you must loudly hiss or tsk at them like an angry cat.",
  "Let the group pick any item in the room that can safely be worn on your head (e.g., an empty box, pot, or clean sock). You must wear this headgear for 3 rounds.",
  "Take your phone, open the front camera, and record a 10-second video reading the instruction manual of an appliance or air freshener as dramatically as possible, then send it to your most active chat.",
  "Call any acquaintance (not with you) and start with: 'Listen, do you know why the wallpaper starts winking at me whenever I look at it?'. Try to keep panic in your voice for 30 seconds.",
  "For the next 3 rounds, you cannot use any affirmative/declarative statements. To everything said to you, you must reply exclusively with counter-questions.",
  "Give the marker to the person on your left. Let them draw a clock face on your arm showing a fictional time. Every time you are asked for the time until the end of the game, you must look at this drawing and read it out.",
  "Take an ice cube (or something freezing), hold it tight in your fist for 1 minute while looking straight into the eyes of the person sitting to your right without changing your facial expression.",
  "Go to any mirror in the house, press your forehead against it, and whisper a children's poem or nursery rhyme for 30 seconds with mysterious pauses.",
  "Open any chat, find the last voice message from a friend, and send a text reply in ALL CAPS with exclamation marks: 'I KNEW IT! DON'T EVER WRITE TO ME ABOUT THIS AGAIN!!!', then ignore their replies for 5 minutes.",
  "Let the group choose two different songs. Your task is to dance in rhythm to one song while loudly singing the lyrics of the second song at the same time without getting thrown off.",
  "Call any 24/7 delivery or hotline and politely ask if they can give you the exact recipe for a perfect mood when everyone around is acting way too serious.",
  "Take any long object (ruler, broom, rolled-up newspaper), hold it over your head like a sword of justice, and stand in an epic guard pose at the room entrance for 1 minute.",
  "Sit on the floor, cross your arms over your chest, and spend 1 minute making kettle-boiling noises (whistling, bubbling, hissing) whenever there is a silence in the room."
];

export default questionsDare;